server:
  port: 8804

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'


spring:
  application:
    name: developer
  datasource:
    url: jdbc:postgresql://localhost:5432/developer
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: com.umasuo.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: email
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: QWERTYUIOPASDFGHJKLZXCVBNM
  expires: 72000

user:
  service:
    uri: http://localhost:8809/
product:
  service:
    uri: http://localhost:8805/

aliyun:
  email:
    region: cn-hangzhou
    accessKeyId: access key
    secret: secret
