server:
  port: 8804

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'


spring:
  application:
    name: developer
  datasource:
    url: jdbc:postgresql://localhost:5432/developer
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: com.umasuo.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ******
    password: ******
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: QWERTYUIOPASDFGHJKLZXCVBNM
  expires: 72000

user:
  service:
    uri: http://localhost:8809/
device-definition:
  service:
    uri: http://localhost:8805/

redis:
  key:
    verify: developer:%s:verify
    reset: developer:%s:reset
    developer: developer:%s

email:
  subject:
    verify: Please verify your email address.
    reset: Reset password.